version: "3"

services:
  database:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "catalog2"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "catalog2"
    volumes:
      - "catalog_postgresql:/var/lib/postgresql/data"
    networks:
      - catalog2

  webserver:
    image: "catalog2:latest"
    build:
      context: .
      dockerfile: "Containerfile"
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgres://catalog2:password@database:5432/catalog2"
      WEB_URL: "0.0.0.0:3000"
      USER_CREDS: |
        [
          {
            "username": "admin",
            "hash": "$$2b$$12$$QkHm2JiQg3WILPe0l/8Vqun7UVLqfSBLAzXiKbffGhs11RSqH7bjS"
          }
        ]
      JWT_KEY: "N9&YMUGmNpP@dy$At6jv$CEoXRA5hEgNy%C3n4mVKQpDkJoFMZ5VxK#&e&7xrYrC5$nai73GE!dGKqxc"
    networks:
      - catalog2
    depends_on:
      database:
        condition: "service_healthy"

volumes:
  catalog_postgresql:

networks:
  catalog2:
