name: Docker Checks

on:
  pull_request:
    branches:
      - main

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Container Build Check
        run: docker build . --file Containerfile --tag catalog2:${{ github.sha }}
