name: Rust

on:
  push:
    branches: [ "main", "workflow" ]
  pull_request:
    branches: [ "main", "workflow" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  rustfmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Format
      run: cargo fmt --check --verbose
      
  sqlx-cli:
    runs-on: ubuntu-latest
    steps:
    - name: Install sqlx-cli
      run: cargo install sqlx-cli
    - uses: actions/upload-artifact@v3
      with:
        name: sqlx-cli
        path: /home/runner/.cargo/bin/sqlx

  check:
    runs-on: ubuntu-latest
    needs: sqlx-cli
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: catalog2
          POSTGRES_USER: catalog2
          POSTGRES_PASSWORD: password
        ports:
        - 5432:5432
    steps:
    - uses: actions/checkout@v4
    - name: Get SQLx-CLI
      uses: actions/download-artifact@v3
      with:
        name: sqlx-cli
        path: /home/runner/.local/bin
    - name: Migrate DB
      run: |
        chmod +x /home/runner/.local/bin/sqlx
        sqlx migrate run
    - name: Check
      run: cargo check

  clippy:
    runs-on: ubuntu-latest
    needs: sqlx-cli
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: catalog2
          POSTGRES_USER: catalog2
          POSTGRES_PASSWORD: password
        ports:
        - 5432:5432
    steps:
    - uses: actions/checkout@v4
    - name: Get SQLx-CLI
      uses: actions/download-artifact@v3
      with:
        name: sqlx-cli
        path: /home/runner/.local/bin
    - name: Migrate DB
      run: |
        chmod +x /home/runner/.local/bin/sqlx
        sqlx migrate run
    - name: Clippy
      run: cargo clippy
      
  test:
    runs-on: ubuntu-latest
    needs: sqlx-cli
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: catalog2
          POSTGRES_USER: catalog2
          POSTGRES_PASSWORD: password
        ports:
        - 5432:5432
    steps:
    - uses: actions/checkout@v4
    - name: Get SQLx-CLI
      uses: actions/download-artifact@v3
      with:
        name: sqlx-cli
        path: /home/runner/.local/bin
    - name: Migrate DB
      run: |
        chmod +x /home/runner/.local/bin/sqlx
        sqlx migrate run
    - name: Tests
      run: cargo test
