name: Rust

on:
  push:
    branches: [ "main", "workflow" ]
  pull_request:
    branches: [ "main", "workflow" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  sqlx-cli:
    runs-on: ubuntu-latest
    steps:
    - name: Install sqlx-cli
      run: cargo install sqlx-cli
    - name: Install where
      run: which sqlx
    - uses: actions/upload-artifact@v3
      with:
        name: sqlx-cli
        path: target/release/sqlx

  rustfmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Format
      run: cargo fmt --check --verbose

  check:
    runs-on: ubuntu-latest
    needs: sqlx-cli
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: catalog2
          POSTGRES_USER: catalog2
          POSTGRES_PASSWORD: password
        ports:
        - 5432:5432
    steps:
    - uses: actions/checkout@v4
    - name: Migrate DB
      run: sqlx migrate run
    - name: Check
      run: cargo check

  clippy:
    runs-on: ubuntu-latest
    needs: sqlx-cli
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: catalog2
          POSTGRES_USER: catalog2
          POSTGRES_PASSWORD: password
        ports:
        - 5432:5432
    steps:
    - uses: actions/checkout@v4
    - name: Migrate DB
      run: sqlx migrate run
    - name: Clippy
      run: cargo clippy
      
  test:
    runs-on: ubuntu-latest
    needs: sqlx-cli
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: catalog2
          POSTGRES_USER: catalog2
          POSTGRES_PASSWORD: password
        ports:
        - 5432:5432
    steps:
    - uses: actions/checkout@v4
    - name: Migrate DB
      run: sqlx migrate run
    - name: Tests
      run: cargo test
