name: Rust Checks

on:
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:

  sqlx-cache-check:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: catalog2
          POSTGRES_USER: catalog2
          POSTGRES_PASSWORD: password
        ports:
        - 5432:5432
    steps:
    - uses: actions/checkout@v4
    - name: Get SQLx-CLI
      run: cargo install sqlx-cli --no-default-features --features native-tls,postgres
    - name: Migrate DB
      run: sqlx migrate run
    - name: sqlx Cache Check
      run: cargo sqlx prepare --check

  rustfmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Format
      run: cargo fmt --check --verbose

  check:
    runs-on: ubuntu-latest
    needs: sqlx-cache-check
    steps:
    - uses: actions/checkout@v4
    - name: Check
      run: SQLX_OFFLINE=true cargo check

  clippy:
    runs-on: ubuntu-latest
    needs: sqlx-cache-check
    steps:
    - uses: actions/checkout@v4
    - name: Clippy
      run: SQLX_OFFLINE=true cargo clippy
      
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: catalog2
          POSTGRES_USER: catalog2
          POSTGRES_PASSWORD: password
        ports:
        - 5432:5432
    steps:
    - uses: actions/checkout@v4
    - name: Get SQLx-CLI
      run: cargo install sqlx-cli --no-default-features --features native-tls,postgres
    - name: Migrate DB
      run: sqlx migrate run
    - name: Tests
      run: cargo test
