name: Rust Checks

on:
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  rustfmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Format
      run: cargo fmt --check --verbose

  check:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: catalog2
          POSTGRES_USER: catalog2
          POSTGRES_PASSWORD: password
        ports:
        - 5432:5432
    steps:
    - uses: actions/checkout@v4
    - name: Get SQLx-CLI
      run: cargo install sqlx-cli
    - name: Migrate DB
      run: sqlx migrate run
    - name: Check
      run: cargo check

  clippy:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: catalog2
          POSTGRES_USER: catalog2
          POSTGRES_PASSWORD: password
        ports:
        - 5432:5432
    steps:
    - uses: actions/checkout@v4
    - name: Get SQLx-CLI
      run: cargo install sqlx-cli
    - name: Migrate DB
      run: sqlx migrate run
    - name: Clippy
      run: cargo clippy
      
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: catalog2
          POSTGRES_USER: catalog2
          POSTGRES_PASSWORD: password
        ports:
        - 5432:5432
    steps:
    - uses: actions/checkout@v4
    - name: Get SQLx-CLI
      run: cargo install sqlx-cli
    - name: Migrate DB
      run: sqlx migrate run
    - name: Tests
      run: cargo test

  sqlx-cache:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: catalog2
          POSTGRES_USER: catalog2
          POSTGRES_PASSWORD: password
        ports:
        - 5432:5432
    steps:
    - uses: actions/checkout@v4
    - name: Get SQLx-CLI
      run: cargo install sqlx-cli
    - name: Migrate DB
      run: sqlx migrate run
    - name: sqlx Cache Check
      run: sqlx prepare --check
