name: Rust

on:
  push:
    branches: [ "main", "workflow" ]
  pull_request:
    branches: [ "main", "workflow" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  sqlx-migration:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: catalog2
          POSTGRES_USER: catalog2
          POSTGRES_PASSWORD: password
        ports:
        - 5432:5432
    steps:
    - uses: actions/checkout@v4
    - name: Install sqlx-cli
      run: cargo install sqlx-cli
    - name: Migrate
      run: sqlx migrate run

  check:
    runs-on: ubuntu-latest
    needs: sqlx-migration
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: catalog2
          POSTGRES_USER: catalog2
          POSTGRES_PASSWORD: password
        ports:
        - 5432:5432
    steps:
    - name: Check
      run: cargo check

  clippy:
    runs-on: ubuntu-latest
    needs: sqlx-migration
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: catalog2
          POSTGRES_USER: catalog2
          POSTGRES_PASSWORD: password
        ports:
        - 5432:5432
    steps:
    - name: Linter
      run: cargo clippy

  rustfmt:
    runs-on: ubuntu-latest
    needs: sqlx-migration
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: catalog2
          POSTGRES_USER: catalog2
          POSTGRES_PASSWORD: password
        ports:
        - 5432:5432
    steps:
    - name: Format
      run: cargo fmt --check --verbose
      
  test:
    runs-on: ubuntu-latest
    needs: sqlx-migration
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: catalog2
          POSTGRES_USER: catalog2
          POSTGRES_PASSWORD: password
        ports:
        - 5432:5432
    steps:
    - name: Tests
      run: cargo test
